Repository bcgov/workbc-wage-subsidy, pull requests merged in 2023-11, with the labels that each got.

#112 TECH-394: Admin client notifications
  .eslintrc.js
  packages/admin-api/src/app.ts
  packages/admin-api/src/controllers/notification.controller.ts
  packages/admin-api/src/routes/notification.route.ts
  packages/admin-api/src/services/claims.service.ts
  packages/admin-api/src/services/notification.service.ts
  packages/admin-api/src/typings/typings.d.ts
  packages/admin-client/src/App.tsx
  packages/admin-client/src/Auth/LoginPage.tsx
  packages/admin-client/src/Auth/authProvider.tsx
  packages/admin-client/src/DataProvider/DataProvider.tsx
  packages/admin-client/src/admin/ready.tsx
  packages/admin-client/src/common/components/NotificationCheck/NotificationCheck.tsx
  packages/admin-client/src/common/components/NotifyButton/NotifyButton.tsx
  packages/admin-client/src/utils/parseCatchments.tsx
  packages/employer-api/.env.sample
  packages/employer-api/src/config/CREATE_SCRIPTS.sql
  packages/employer-api/src/config/config.ts
  packages/employer-api/src/controllers/application.controller.ts
  packages/employer-api/src/controllers/event.controller.ts
  packages/employer-api/src/services/claim.service.ts
  packages/employer-api/src/services/formAPI.service.ts
  packages/form-api/.env.sample
  packages/form-api/src/app.ts
  packages/form-api/src/controllers/address.controller.ts
  packages/form-api/src/controllers/claim.controller.ts
  packages/form-api/src/controllers/email.controller.ts
  packages/form-api/src/services/email.service.ts
  packages/form-api/src/services/notification.service.ts
  packages/form-api/src/templates/notification.template.ts
  packages/form-api/src/templates/received.template.ts
  packages/typings/emailData.d.ts
Labels: enhancement

#106 CD fix
  .github/workflows/CD-next-claims.yml
  .github/workflows/CD.yml
  packages/admin-client/package.json
  packages/employer-api/package.json
  packages/employer-client/package.json
  packages/form-api/package.json
  packages/static/package.json
Labels: bug

#125 TECH-547: Employer client: internal server error after every form submission
  packages/employer-api/src/controllers/event.controller.ts
  packages/form-api/src/controllers/email.controller.ts
  packages/form-api/src/templates/notification.template.ts
Labels: bug

#129 TECH-547-fix: Wrapping status 500 in a catch statement instead of checking for status on returned object.
  packages/employer-api/src/controllers/event.controller.ts
Labels: bug

#126 TECH-549, TECH-550, TECH-551: fix issues with SelectApplication list
  packages/employer-client/src/Claims/ClaimCreateSelectApplication.tsx
Labels: bug

#127 TECH-552: restrict Shared With column to business bceid users
  packages/employer-client/src/Applications/ApplicationList.tsx
  packages/employer-client/src/Claims/ClaimList.tsx
Labels: bug

#130 TECH-546, TECH-554: Support custom sorting by date, remove checkboxes from SelectApplication list
  packages/admin-api/src/controllers/application.controller.ts
  packages/admin-api/src/controllers/claim.controller.ts
  packages/admin-api/src/lib/transactions.ts
  packages/admin-api/src/services/application.service.ts
  packages/admin-api/src/services/claims.service.ts
  packages/admin-client/src/Applications/ApplicationList.tsx
  packages/admin-client/src/Claims/ClaimList.tsx
  packages/employer-api/src/controllers/application.controller.ts
  packages/employer-api/src/controllers/claim.controller.ts
  packages/employer-api/src/services/application.service.ts
  packages/employer-api/src/services/claim.service.ts
  packages/employer-client/src/Applications/ApplicationList.tsx
  packages/employer-client/src/Claims/ClaimCreateSelectApplication.tsx
  packages/employer-client/src/Claims/ClaimList.tsx
  packages/employer-client/src/common/components/CustomDatagrid/CustomDatagrid.tsx
Labels: bug, enhancement

#131 TECH-545: remove unsupported catchments from permissions query results
  packages/admin-api/src/services/permission.service.ts
Labels: bug

#136 Fix build
  packages/employer-client/src/common/components/CustomDatagrid/CustomDatagrid.tsx
Labels: bug

#139 TECH-599: do not sync until employer record known to exist
  packages/employer-client/src/App.tsx
  packages/employer-client/src/Applications/ApplicationList.tsx
  packages/employer-client/src/Claims/ClaimList.tsx
  packages/employer-client/src/UserProfileModal.tsx
  packages/employer-client/src/common/contexts/EmployerContext.tsx
Labels: bug

#137 TECH594: Move emailing and notifications to Employer API
  packages/employer-api/.env.sample
  packages/employer-api/src/config/config.ts
  packages/employer-api/src/constants/centres.json
  packages/employer-api/src/controllers/application.controller.ts
  packages/employer-api/src/controllers/email.controller.ts
  packages/employer-api/src/controllers/event.controller.ts
  packages/employer-api/src/services/common.service.ts
  packages/employer-api/src/services/email.service.ts
  packages/employer-api/src/services/formAPI.service.ts
  packages/employer-api/src/services/notification.service.ts
  packages/employer-api/src/templates/notification.template.ts
  packages/employer-api/src/templates/received.template.ts
  packages/employer-api/src/typings/emailData.d.ts
  packages/employer-api/src/utils/htmlEmail.js
  packages/form-api/.env.sample
  packages/form-api/src/app.ts
  packages/form-api/src/config/config.ts
  packages/form-api/src/config/db-config.ts
  packages/form-api/src/controllers/claim.controller.ts
  packages/form-api/src/controllers/wage.controller.ts
  packages/form-api/src/routes/claim.route.ts
  packages/form-api/src/routes/email.route.ts
  packages/form-api/src/routes/wage.route.ts
  packages/form-api/src/services/claim.service.ts
  packages/form-api/src/services/wage.service.ts
Labels: enhancement
